<?php
/**
 * Built-in Migration Bridge operator copy.
 *
 * @package SeoGeoMigrationBridge
 */

declare(strict_types=1);

namespace SeoGeo\MigrationBridge\Operator;

/**
 * Resolves one key-complete EN/ES operator catalog without runtime dependencies.
 */
final class OperatorCopy {
	/**
	 * Explicit locale override.
	 *
	 * @var string|null
	 */
	private ?string $locale;

	/**
	 * Create a copy resolver.
	 *
	 * @param string|null $locale Optional locale override.
	 */
	public function __construct( ?string $locale = null ) {
		$this->locale = $locale;
	}

	/**
	 * Return all shipped operator catalogs.
	 *
	 * @return array<string,array<string,string>>
	 */
	public static function catalogs(): array {
		return array(
			'en' => array(
				'page_title'                     => 'SEO/GEO Migration Bridge',
				'menu_title'                     => 'SEO/GEO Migration',
				'intro'                          => 'Review migration status and the safest next step. Viewing this screen is read-only. Explicit baseline and dependency-review actions store only bounded planning evidence; they do not execute migration, cutover, rollback, or content/theme/plugin mutations.',
				'forbidden'                      => 'You do not have permission to view Migration Bridge status.',
				'overview_heading'               => 'Migration status',
				'review_heading'                 => 'Review status',
				'dependency_heading'             => 'Dependency classifications',
				'dependency_detail_heading'      => 'Dependency detail',
				'dependency_detail_help'         => 'UNKNOWN items are shown first so they can be reviewed before sandbox migration. Recording a review stores only a bounded planning decision and does not change the dependency graph classification used by production cutover.',
				'dependency_review_help'         => 'Review each UNKNOWN component explicitly before sandbox acceptance. These decisions are exported separately as planning evidence and never authorize production deactivation or theme changes.',
				'dependency_review_saved'        => 'Dependency review decision saved as planning evidence.',
				'dependency_review_cleared'      => 'Dependency review decision cleared.',
				'sandbox_handoff_heading'        => 'Sandbox handoff',
				'sandbox_preflight_heading'      => 'Sandbox readiness',
				'sandbox_preflight_help'         => 'Migration can run only after every isolation and recovery guard below is satisfied. A sandbox may use a distinct origin or an explicitly isolated same-origin subdirectory.',
				'sandbox_handoff_help'           => 'Download a privacy-bounded JSON manifest with baseline identity, runtime metadata, raw dependency classifications and bounded operator review decisions. It does not contain post bodies, builder payloads, credentials, database dumps or uploads.',
				'sandbox_handoff_button'         => 'Download sandbox handoff JSON',
				'clone_heading'                  => 'Portable Clone Engine',
				'clone_help'                     => 'Portable Clone now inventories the source in read-only resumable batches before any export/import payload is created.',
				'clone_job_created'              => 'Portable Clone planning job created.',
				'clone_inventory_heading'        => 'Read-only source inventory',
				'clone_inventory_help'           => 'Inventory reads WordPress-prefix table metadata and hashes accepted uploads/plugin/theme files in bounded batches. It never copies or changes production data.',
				'clone_inventory_start'          => 'Start source inventory',
				'clone_inventory_continue'       => 'Continue source inventory',
				'clone_inventory_complete'       => 'Source inventory complete.',
				'clone_inventory_running'        => 'Source inventory progress saved. Continue with another bounded batch.',
				'clone_inventory_blocked'        => 'Source inventory stopped on a safety blocker.',
				'clone_inventory_batch_label'    => 'Files per request',
				'clone_inventory_batch_help'     => 'Recommended: 100. Use 25-50 on limited shared hosting and 200-500 on faster servers.',
				'label_clone_db_tables'          => 'Database tables',
				'label_clone_db_rows'            => 'Estimated database rows',
				'label_clone_db_bytes'           => 'Estimated database bytes',
				'label_clone_files'              => 'Accepted files',
				'label_clone_bytes'              => 'Accepted file bytes',
				'label_clone_excluded'           => 'Excluded entries',
				'label_clone_symlinks'           => 'Excluded symlinks',
				'label_clone_unreadable'         => 'Unreadable entries',
				'label_clone_fingerprint'        => 'Source fingerprint',
				'label_clone_inventory_status'   => 'Inventory status',
				'clone_database_export_heading'   => 'Resumable database export',
				'clone_database_export_help'      => 'After inventory completes, export only the inventoried WordPress-prefix tables into a private server-side workspace. Production database access remains read-only.',
				'clone_database_export_start'     => 'Start database export',
				'clone_database_export_continue'  => 'Continue database export',
				'clone_database_export_running'   => 'Database export progress saved. Continue with another bounded row batch.',
				'clone_database_export_complete'  => 'Database export completed and its private manifest was hashed.',
				'clone_database_export_blocked'   => 'Database export stopped on a bounded safety or I/O blocker.',
				'clone_database_batch_label'      => 'Rows per request',
				'clone_database_batch_help'       => 'Recommended: 100. Use 25-50 on limited hosting and 200-500 on faster servers.',
				'label_clone_export_tables_done'  => 'Tables completed',
				'label_clone_export_rows'         => 'Rows exported',
				'label_clone_export_chunks'       => 'Database chunks',
				'label_clone_export_bytes'        => 'Private payload bytes',
				'label_clone_export_manifest'     => 'Database manifest SHA-256',
				'clone_local_button'             => 'Plan local sandbox clone',
				'clone_export_button'            => 'Plan portable export',
				'clone_import_button'            => 'Plan portable import',
				'clone_latest_heading'           => 'Latest clone job',
				'label_clone_job_id'             => 'Job ID',
				'label_clone_operation'          => 'Operation',
				'label_clone_phase'              => 'Phase',
				'label_clone_status'             => 'Status',
				'label_clone_progress'           => 'Progress',
				'next_step_heading'              => 'Recommended next step',
				'privacy_heading'                => 'Safety and privacy',
				'privacy_text'                   => 'This screen shows bounded status metadata only. Baseline capture uses anonymous same-origin public requests and stores fingerprints/SEO signals. Dependency review stores only component IDs, fixed decision/reason codes and a timestamp; no post bodies, builder payloads, credentials, arbitrary option values or raw recovery artifacts are stored in review evidence.',
				'label_baseline'                 => 'SEO/GEO baseline',
				'label_dependency_plan'          => 'Dependency plan',
				'label_cutover'                  => 'Production cutover',
				'label_final_report'             => 'Final migration report',
				'label_sandbox_readiness'        => 'Sandbox readiness',
				'label_source_origin'            => 'Production baseline origin',
				'label_current_origin'           => 'Current sandbox origin',
				'label_sandbox_mode'             => 'Sandbox mode',
				'label_source_path'              => 'Production baseline path',
				'label_current_path'             => 'Current sandbox path',
				'label_location_isolated'        => 'Sandbox location isolated',
				'label_storage_isolated'         => 'Storage/runtime isolated',
				'label_distinct_origin'          => 'Distinct host/protocol origin',
				'label_search_disabled'          => 'Search visibility disabled',
				'label_outbound_safe'            => 'Outbound transactions safe',
				'label_backups_ready'            => 'Fresh recovery references confirmed',
				'label_destination_theme'        => 'Destination theme active',
				'label_review_complete'          => 'UNKNOWN review complete',
				'label_sandbox_blockers'         => 'Sandbox blockers',
				'sandbox_no_blockers'            => 'None',
				'label_bridge_disposition'       => 'Migration Bridge disposition',
				'label_blocking_review'          => 'Blocking review items',
				'label_advisory_review'          => 'Advisory review items',
				'label_classification'           => 'Classification',
				'label_count'                    => 'Count',
				'label_component'                => 'Component',
				'label_type'                     => 'Type',
				'label_reason'                   => 'Reason',
				'label_active'                   => 'Active',
				'label_resources'                => 'Resources',
				'label_review'                   => 'Operator review',
				'label_action'                   => 'Action',
				'label_reviewed_unknown'         => 'Reviewed UNKNOWN items',
				'label_unreviewed_unknown'       => 'Pending UNKNOWN items',
				'review_pending'                 => 'Pending',
				'review_unreviewed'              => 'Unreviewed',
				'review_save'                    => 'Save review',
				'yes'                            => 'Yes',
				'no'                             => 'No',
				'status_ready'                   => 'Ready',
				'status_missing'                 => 'Missing',
				'status_accepted'                => 'Accepted',
				'status_pending'                 => 'Pending',
				'status_needs_attention'         => 'Needs attention',
				'status_not_applicable'          => 'Not applicable',
				'disposition_remove'             => 'Remove after final verification',
				'disposition_retain_audit_only'  => 'Retain in audit-only mode',
				'disposition_retain_operational' => 'Retain while migration is operational',
				'next_capture_baseline'          => 'Capture and persist the public SEO/GEO baseline before planning migration changes.',
				'baseline_capture_button'        => 'Start safe SEO/GEO baseline capture',
				'baseline_continue'              => 'Continue baseline capture',
				'baseline_progress'              => 'Capture progress: %1$d of %2$d public resources (%3$d%%). Progress is saved after every small batch.',
				'baseline_progress_notice'       => 'Progress saved. Choose the next batch size and continue when ready; if the connection closes, return here and resume safely.',
				'batch_size_label'               => 'Batch size (1-20)',
				'batch_size_help'                => 'Recommended: 10 on shared hosting. Use 1-5 for very limited servers and 15-20 for faster servers.',
				'batch_size_current'             => 'Current batch size: %d public pages per request.',
				'baseline_capture_help'          => 'This explicit action anonymously reads same-origin public URLs in small resumable batches and stores only the Migration Bridge baseline/progress. It does not change the theme, plugins, content, permalinks, or public SEO output.',
				'baseline_capture_success'       => 'SEO/GEO baseline captured and stored successfully.',
				'baseline_capture_exists'        => 'A baseline already exists. It was not replaced.',
				'baseline_capture_error'         => 'The baseline could not be captured or stored. No migration action was executed.',
				'next_sandbox_preflight'         => 'Complete every sandbox isolation, recovery and dependency-review guard before running migration actions.',
				'next_continue_migration'        => 'Continue the sandbox migration and parity workflow before production cutover.',
				'next_complete_cutover'          => 'Complete and explicitly accept the reversible production cutover before final handoff.',
				'next_generate_report'           => 'Generate and persist the final migration report after the accepted cutover.',
				'next_resolve_blockers'          => 'Resolve blocking migration review items before the bridge can be retired.',
				'next_review_advisories'         => 'Review the remaining advisory items. Runtime migration work is complete; the bridge may remain audit-only if desired.',
				'next_remove_bridge'             => 'Archive the final handoff evidence and remove the Migration Bridge after final operational verification.',
			),
			'es' => array(
				'page_title'                     => 'Puente de migración SEO/GEO',
				'menu_title'                     => 'Migración SEO/GEO',
				'intro'                          => 'Revisa el estado de la migración y el siguiente paso más seguro. Consultar esta pantalla es de solo lectura. Las acciones explícitas de línea base y revisión de dependencias guardan solo evidencia de planificación acotada; no ejecutan migración, cambio a producción, reversión ni cambios de contenido, tema o plugins.',
				'forbidden'                      => 'No tienes permisos para consultar el estado del Puente de migración.',
				'overview_heading'               => 'Estado de la migración',
				'review_heading'                 => 'Estado de revisión',
				'dependency_heading'             => 'Clasificaciones de dependencias',
				'dependency_detail_heading'      => 'Detalle de dependencias',
				'dependency_detail_help'         => 'Los elementos UNKNOWN aparecen primero para revisarlos antes de migrar en sandbox. Guardar una revisión registra solo una decisión de planificación acotada y no cambia la clasificación del grafo usada para autorizar el cambio a producción.',
				'dependency_review_help'         => 'Revisa explícitamente cada componente UNKNOWN antes de aceptar el sandbox. Estas decisiones se exportan por separado como evidencia de planificación y nunca autorizan por sí solas desactivar plugins o cambiar el tema en producción.',
				'dependency_review_saved'        => 'La decisión de revisión de la dependencia se guardó como evidencia de planificación.',
				'dependency_review_cleared'      => 'La decisión de revisión de la dependencia se eliminó.',
				'sandbox_handoff_heading'        => 'Entrega al sandbox',
				'sandbox_preflight_heading'      => 'Preparación del sandbox',
				'sandbox_preflight_help'         => 'La migración solo puede ejecutarse cuando se cumplan todas las protecciones de aislamiento y recuperación. El sandbox puede usar un origen distinto o una subcarpeta del mismo origen aislada explícitamente.',
				'sandbox_handoff_help'           => 'Descarga un manifiesto JSON acotado por privacidad con la identidad de la línea base, metadatos del runtime, clasificaciones originales de dependencias y decisiones acotadas de revisión. No incluye cuerpos de entradas, cargas de constructores, credenciales, volcados de base de datos ni uploads.',
				'sandbox_handoff_button'         => 'Descargar JSON de sandbox',
				'clone_heading'                  => 'Motor de clon portátil',
				'clone_help'                     => 'El clon portátil ahora inventaría el origen en lotes reanudables y de solo lectura antes de crear cualquier carga de exportación o importación.',
				'clone_job_created'              => 'Se creó el trabajo de planificación del clon portátil.',
				'clone_inventory_heading'        => 'Inventario del origen de solo lectura',
				'clone_inventory_help'           => 'El inventario lee metadatos de las tablas del prefijo WordPress y calcula hashes de archivos aceptados de uploads/plugins/temas en lotes acotados. Nunca copia ni modifica datos de producción.',
				'clone_inventory_start'          => 'Iniciar inventario del origen',
				'clone_inventory_continue'       => 'Continuar inventario del origen',
				'clone_inventory_complete'       => 'Inventario del origen completado.',
				'clone_inventory_running'        => 'Progreso del inventario guardado. Continúa con otro lote acotado.',
				'clone_inventory_blocked'        => 'El inventario se detuvo por un bloqueo de seguridad.',
				'clone_inventory_batch_label'    => 'Archivos por petición',
				'clone_inventory_batch_help'     => 'Recomendado: 100. Usa 25-50 en hosting compartido limitado y 200-500 en servidores más rápidos.',
				'label_clone_db_tables'          => 'Tablas de base de datos',
				'label_clone_db_rows'            => 'Filas estimadas de base de datos',
				'label_clone_db_bytes'           => 'Bytes estimados de base de datos',
				'label_clone_files'              => 'Archivos aceptados',
				'label_clone_bytes'              => 'Bytes de archivos aceptados',
				'label_clone_excluded'           => 'Entradas excluidas',
				'label_clone_symlinks'           => 'Enlaces simbólicos excluidos',
				'label_clone_unreadable'         => 'Entradas no legibles',
				'label_clone_fingerprint'        => 'Huella del origen',
				'label_clone_inventory_status'   => 'Estado del inventario',
				'clone_database_export_heading'   => 'Exportación reanudable de base de datos',
				'clone_database_export_help'      => 'Cuando termina el inventario, exporta solo las tablas inventariadas del prefijo WordPress a un espacio privado del servidor. El acceso a la base de datos de producción sigue siendo de solo lectura.',
				'clone_database_export_start'     => 'Iniciar exportación de base de datos',
				'clone_database_export_continue'  => 'Continuar exportación de base de datos',
				'clone_database_export_running'   => 'Progreso de exportación guardado. Continúa con otro lote acotado de filas.',
				'clone_database_export_complete'  => 'La exportación de base de datos terminó y su manifiesto privado quedó verificado con hash.',
				'clone_database_export_blocked'   => 'La exportación de base de datos se detuvo por un bloqueo acotado de seguridad o E/S.',
				'clone_database_batch_label'      => 'Filas por petición',
				'clone_database_batch_help'       => 'Recomendado: 100. Usa 25-50 en hosting limitado y 200-500 en servidores más rápidos.',
				'label_clone_export_tables_done'  => 'Tablas completadas',
				'label_clone_export_rows'         => 'Filas exportadas',
				'label_clone_export_chunks'       => 'Fragmentos de base de datos',
				'label_clone_export_bytes'        => 'Bytes de carga privada',
				'label_clone_export_manifest'     => 'SHA-256 del manifiesto de base de datos',
				'clone_local_button'             => 'Planificar clon local del sandbox',
				'clone_export_button'            => 'Planificar exportación portátil',
				'clone_import_button'            => 'Planificar importación portátil',
				'clone_latest_heading'           => 'Último trabajo de clonación',
				'label_clone_job_id'             => 'ID del trabajo',
				'label_clone_operation'          => 'Operación',
				'label_clone_phase'              => 'Fase',
				'label_clone_status'             => 'Estado',
				'label_clone_progress'           => 'Progreso',
				'next_step_heading'              => 'Siguiente paso recomendado',
				'privacy_heading'                => 'Seguridad y privacidad',
				'privacy_text'                   => 'Esta pantalla muestra únicamente metadatos de estado acotados. La captura de línea base usa solicitudes públicas anónimas del mismo origen y guarda huellas/señales SEO. La revisión de dependencias guarda solo IDs de componentes, códigos fijos de decisión/motivo y una marca temporal; no guarda cuerpos de entradas, cargas de constructores, credenciales, valores arbitrarios de opciones ni artefactos de recuperación en bruto.',
				'label_baseline'                 => 'Línea base SEO/GEO',
				'label_dependency_plan'          => 'Plan de dependencias',
				'label_cutover'                  => 'Cambio a producción',
				'label_final_report'             => 'Informe final de migración',
				'label_sandbox_readiness'        => 'Preparación del sandbox',
				'label_source_origin'            => 'Origen de la línea base de producción',
				'label_current_origin'           => 'Origen actual del sandbox',
				'label_sandbox_mode'             => 'Modo del sandbox',
				'label_source_path'              => 'Ruta de la línea base de producción',
				'label_current_path'             => 'Ruta actual del sandbox',
				'label_location_isolated'        => 'Ubicación del sandbox aislada',
				'label_storage_isolated'         => 'Almacenamiento/runtime aislado',
				'label_distinct_origin'          => 'Origen host/protocolo distinto',
				'label_search_disabled'          => 'Visibilidad para buscadores desactivada',
				'label_outbound_safe'            => 'Transacciones salientes seguras',
				'label_backups_ready'            => 'Referencias de recuperación recientes confirmadas',
				'label_destination_theme'        => 'Tema de destino activo',
				'label_review_complete'          => 'Revisión UNKNOWN completa',
				'label_sandbox_blockers'         => 'Bloqueos del sandbox',
				'sandbox_no_blockers'            => 'Ninguno',
				'label_bridge_disposition'       => 'Disposición del Puente de migración',
				'label_blocking_review'          => 'Elementos de revisión bloqueantes',
				'label_advisory_review'          => 'Elementos de revisión recomendados',
				'label_classification'           => 'Clasificación',
				'label_count'                    => 'Cantidad',
				'label_component'                => 'Componente',
				'label_type'                     => 'Tipo',
				'label_reason'                   => 'Motivo',
				'label_active'                   => 'Activo',
				'label_resources'                => 'Recursos',
				'label_review'                   => 'Revisión del operador',
				'label_action'                   => 'Acción',
				'label_reviewed_unknown'         => 'UNKNOWN revisados',
				'label_unreviewed_unknown'       => 'UNKNOWN pendientes',
				'review_pending'                 => 'Pendiente',
				'review_unreviewed'              => 'Sin revisar',
				'review_save'                    => 'Guardar revisión',
				'yes'                            => 'Sí',
				'no'                             => 'No',
				'status_ready'                   => 'Listo',
				'status_missing'                 => 'Falta',
				'status_accepted'                => 'Aceptado',
				'status_pending'                 => 'Pendiente',
				'status_needs_attention'         => 'Requiere atención',
				'status_not_applicable'          => 'No aplica',
				'disposition_remove'             => 'Eliminar tras la verificación final',
				'disposition_retain_audit_only'  => 'Mantener solo para auditoría',
				'disposition_retain_operational' => 'Mantener mientras la migración siga operativa',
				'next_capture_baseline'          => 'Captura y guarda la línea base pública SEO/GEO antes de planificar cambios de migración.',
				'baseline_capture_button'        => 'Iniciar captura segura de línea base SEO/GEO',
				'baseline_continue'              => 'Continuar captura de línea base',
				'baseline_progress'              => 'Progreso de captura: %1$d de %2$d recursos públicos (%3$d%%). El progreso se guarda después de cada lote pequeño.',
				'baseline_progress_notice'       => 'Progreso guardado. Elige el tamaño del siguiente lote y continúa cuando quieras; si se corta la conexión, vuelve aquí y reanuda de forma segura.',
				'batch_size_label'               => 'Tamaño de lote (1-20)',
				'batch_size_help'                => 'Recomendado: 10 en hosting compartido. Usa 1-5 para servidores muy limitados y 15-20 para servidores más rápidos.',
				'batch_size_current'             => 'Lote actual: %d páginas públicas por petición.',
				'baseline_capture_help'          => 'Esta acción explícita lee de forma anónima URLs públicas del mismo origen en lotes pequeños y reanudables, y guarda únicamente la línea base/progreso del Puente de migración. No cambia el tema, plugins, contenido, enlaces permanentes ni la salida SEO pública.',
				'baseline_capture_success'       => 'La línea base SEO/GEO se capturó y guardó correctamente.',
				'baseline_capture_exists'        => 'Ya existe una línea base. No se ha reemplazado.',
				'baseline_capture_error'         => 'No se pudo capturar o guardar la línea base. No se ejecutó ninguna acción de migración.',
				'next_sandbox_preflight'         => 'Completa todas las protecciones de aislamiento, recuperación y revisión de dependencias del sandbox antes de ejecutar acciones de migración.',
				'next_continue_migration'        => 'Continúa la migración en sandbox y la validación de paridad antes del cambio a producción.',
				'next_complete_cutover'          => 'Completa y acepta explícitamente el cambio reversible a producción antes de la entrega final.',
				'next_generate_report'           => 'Genera y guarda el informe final de migración después de aceptar el cambio a producción.',
				'next_resolve_blockers'          => 'Resuelve los elementos bloqueantes de revisión antes de retirar el puente.',
				'next_review_advisories'         => 'Revisa los elementos recomendados restantes. El trabajo operativo de migración está completo; el puente puede mantenerse solo para auditoría si se desea.',
				'next_remove_bridge'             => 'Archiva la evidencia final de entrega y elimina el Puente de migración después de la verificación operativa final.',
			),
		);
	}

	/**
	 * Resolve one localized key with English fallback.
	 *
	 * @param string $key Catalog key.
	 */
	public function text( string $key ): string {
		$catalogs = self::catalogs();
		$locale   = $this->locale ?? get_user_locale();
		$language = str_starts_with( strtolower( $locale ), 'es' ) ? 'es' : 'en';

		return $catalogs[ $language ][ $key ] ?? $catalogs['en'][ $key ] ?? $key;
	}
}
