<?php
/**
 * Corporate final inner-page mockups owned by the Corporate preset.
 *
 * The file is intentionally included once per registered page pattern. It does
 * not declare functions or classes so repeated inclusion remains safe.
 *
 * @package SeoGeoTheme
 */

declare(strict_types=1);

$seo_geo_pattern_key = isset( $seo_geo_pattern_key ) && is_string( $seo_geo_pattern_key ) ? $seo_geo_pattern_key : '';
$seo_geo_asset       = trailingslashit( get_template_directory_uri() ) . 'assets/images/presets/corporate/';
$seo_geo_copy_path   = seo_geo_theme_preset_root() . '/corporate/mockup-copy.json';
$seo_geo_copy        = null;

if ( is_readable( $seo_geo_copy_path ) && function_exists( 'wp_json_file_decode' ) ) {
	$seo_geo_copy = wp_json_file_decode( $seo_geo_copy_path, array( 'associative' => true ) );
}

if ( ! is_array( $seo_geo_copy ) ) {
	return;
}

$seo_geo_locales = $seo_geo_copy['locales'] ?? null;
if ( ! is_array( $seo_geo_locales ) ) {
	return;
}

$seo_geo_locale      = seo_geo_theme_preset_locale();
$seo_geo_locale_copy = $seo_geo_locales[ $seo_geo_locale ] ?? $seo_geo_locales['en_US'] ?? null;
if ( ! is_array( $seo_geo_locale_copy ) ) {
	return;
}

$seo_geo_page = $seo_geo_locale_copy[ $seo_geo_pattern_key ] ?? null;
if ( ! is_array( $seo_geo_page ) ) {
	return;
}

$seo_geo_text = static function ( array $page, string $key ): string {
	$value = $page[ $key ] ?? '';

	return is_string( $value ) ? $value : '';
};
?>
<!-- wp:group {"tagName":"section","align":"wide","className":"seo-geo-corporate-native-hero seo-geo-corporate-inner-hero","layout":{"type":"constrained"}} -->
<section class="wp-block-group alignwide seo-geo-corporate-native-hero seo-geo-corporate-inner-hero">
	<!-- wp:columns {"verticalAlignment":"center","className":"seo-geo-corporate-native-hero__grid"} -->
	<div class="wp-block-columns are-vertically-aligned-center seo-geo-corporate-native-hero__grid">
		<!-- wp:column {"verticalAlignment":"center"} --><div class="wp-block-column is-vertically-aligned-center"><!-- wp:group {"className":"seo-geo-corporate-native-hero__copy","layout":{"type":"constrained"}} --><div class="wp-block-group seo-geo-corporate-native-hero__copy"><!-- wp:paragraph {"className":"seo-geo-corporate-eyebrow"} --><p class="seo-geo-corporate-eyebrow"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'eyebrow' ) ); ?></p><!-- /wp:paragraph --><!-- wp:paragraph {"fontSize":"xl","className":"seo-geo-corporate-lead seo-geo-content-slot--page-lead seo-geo-placeholder--copy"} --><p class="has-xl-font-size seo-geo-corporate-lead seo-geo-content-slot--page-lead seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'lead' ) ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
		<!-- wp:column {"verticalAlignment":"center"} --><div class="wp-block-column is-vertically-aligned-center"><!-- wp:image {"sizeSlug":"full","linkDestination":"none","className":"seo-geo-corporate-mockup-media seo-geo-content-slot--page-media seo-geo-placeholder--media"} --><figure class="wp-block-image size-full seo-geo-corporate-mockup-media seo-geo-content-slot--page-media seo-geo-placeholder--media"><img src="<?php echo esc_url( $seo_geo_asset . ( 'about' === $seo_geo_pattern_key ? 'placeholder-about.svg' : ( 'work' === $seo_geo_pattern_key ? 'placeholder-case.svg' : 'placeholder-hero.svg' ) ) ); ?>" alt="" width="1200" height="760" loading="lazy" decoding="async"/></figure><!-- /wp:image --></div><!-- /wp:column -->
	</div><!-- /wp:columns -->
</section>
<!-- /wp:group -->

<?php if ( 'services' === $seo_geo_pattern_key ) : ?>
<!-- wp:group {"tagName":"section","align":"wide","className":"seo-geo-corporate-native-section","layout":{"type":"constrained"}} -->
<section class="wp-block-group alignwide seo-geo-corporate-native-section"><div class="wp-block-group seo-geo-corporate-section-heading"><p class="seo-geo-corporate-eyebrow"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'intro_label' ) ); ?></p><h2 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'intro_title' ) ); ?></h2><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'intro_body' ) ); ?></p></div>
<div class="wp-block-columns seo-geo-corporate-card-grid"><div class="wp-block-column seo-geo-corporate-card seo-geo-corporate-card--featured"><p class="seo-geo-corporate-card__index">01</p><h3 class="wp-block-heading seo-geo-content-slot--service-1-title seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'service_1' ) ); ?></h3><p class="seo-geo-content-slot--service-1-body seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'service_1_body' ) ); ?></p></div><div class="wp-block-column seo-geo-corporate-card"><p class="seo-geo-corporate-card__index">02</p><h3 class="wp-block-heading seo-geo-content-slot--service-2-title seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'service_2' ) ); ?></h3><p class="seo-geo-content-slot--service-2-body seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'service_2_body' ) ); ?></p></div><div class="wp-block-column seo-geo-corporate-card"><p class="seo-geo-corporate-card__index">03</p><h3 class="wp-block-heading seo-geo-content-slot--service-3-title seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'service_3' ) ); ?></h3><p class="seo-geo-content-slot--service-3-body seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'service_3_body' ) ); ?></p></div></div></section>
<!-- /wp:group -->
<!-- wp:group {"tagName":"section","align":"full","className":"seo-geo-corporate-native-process","layout":{"type":"constrained"}} --><section class="wp-block-group alignfull seo-geo-corporate-native-process"><div class="wp-block-group seo-geo-corporate-section-heading"><p class="seo-geo-corporate-eyebrow"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'process_label' ) ); ?></p><h2 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'process_title' ) ); ?></h2><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'process_body' ) ); ?></p></div><div class="wp-block-columns seo-geo-corporate-process-grid"><div class="wp-block-column seo-geo-corporate-process-step"><p class="seo-geo-corporate-process-step__number">01</p><h3 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'process_1' ) ); ?></h3></div><div class="wp-block-column seo-geo-corporate-process-step"><p class="seo-geo-corporate-process-step__number">02</p><h3 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'process_2' ) ); ?></h3></div><div class="wp-block-column seo-geo-corporate-process-step"><p class="seo-geo-corporate-process-step__number">03</p><h3 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'process_3' ) ); ?></h3></div></div></section><!-- /wp:group -->
<?php elseif ( 'work' === $seo_geo_pattern_key ) : ?>
<!-- wp:group {"tagName":"section","align":"wide","className":"seo-geo-corporate-native-section seo-geo-corporate-featured-work","layout":{"type":"constrained"}} --><section class="wp-block-group alignwide seo-geo-corporate-native-section seo-geo-corporate-featured-work"><div class="wp-block-columns are-vertically-aligned-center seo-geo-corporate-featured-work__grid"><div class="wp-block-column is-vertically-aligned-center" style="flex-basis:58%"><figure class="wp-block-image size-full seo-geo-corporate-mockup-media seo-geo-placeholder--media"><img src="<?php echo esc_url( $seo_geo_asset . 'placeholder-case.svg' ); ?>" alt="" width="1200" height="760" loading="lazy" decoding="async"/></figure></div><div class="wp-block-column is-vertically-aligned-center" style="flex-basis:42%"><p class="seo-geo-corporate-eyebrow"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'intro_label' ) ); ?></p><h2 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'intro_title' ) ); ?></h2><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'intro_body' ) ); ?></p></div></div></section><!-- /wp:group -->
<!-- wp:group {"tagName":"section","align":"wide","className":"seo-geo-corporate-native-section seo-geo-corporate-native-proof","layout":{"type":"constrained"}} --><section class="wp-block-group alignwide seo-geo-corporate-native-section seo-geo-corporate-native-proof"><div class="wp-block-group seo-geo-corporate-section-heading"><p class="seo-geo-corporate-eyebrow"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'proof_label' ) ); ?></p><h2 class="wp-block-heading seo-geo-content-slot--proof-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'proof_title' ) ); ?></h2></div><div class="wp-block-columns seo-geo-corporate-card-grid"><div class="wp-block-column seo-geo-corporate-card"><p class="seo-geo-corporate-card__index">01</p><h3 class="wp-block-heading seo-geo-content-slot--proof-1-title seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'proof_1' ) ); ?></h3></div><div class="wp-block-column seo-geo-corporate-card"><p class="seo-geo-corporate-card__index">02</p><h3 class="wp-block-heading seo-geo-content-slot--proof-2-title seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'proof_2' ) ); ?></h3></div><div class="wp-block-column seo-geo-corporate-card"><p class="seo-geo-corporate-card__index">03</p><h3 class="wp-block-heading seo-geo-content-slot--proof-3-title seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'proof_3' ) ); ?></h3></div></div></section><!-- /wp:group -->
<!-- wp:group {"tagName":"section","align":"full","className":"seo-geo-corporate-native-process seo-geo-corporate-case-study","layout":{"type":"constrained"}} --><section class="wp-block-group alignfull seo-geo-corporate-native-process seo-geo-corporate-case-study"><p class="seo-geo-corporate-eyebrow"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'case_label' ) ); ?></p><h2 class="wp-block-heading seo-geo-content-slot--case-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'case_title' ) ); ?></h2><p class="seo-geo-content-slot--case-intro seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'case_intro' ) ); ?></p><div class="wp-block-columns seo-geo-corporate-process-grid"><div class="wp-block-column seo-geo-corporate-process-step"><h3 class="wp-block-heading"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'challenge' ) ); ?></h3><p class="seo-geo-content-slot--case-challenge-body seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'case_prompt' ) ); ?></p></div><div class="wp-block-column seo-geo-corporate-process-step"><h3 class="wp-block-heading"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'approach' ) ); ?></h3><p class="seo-geo-content-slot--case-approach-body seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'case_prompt' ) ); ?></p></div><div class="wp-block-column seo-geo-corporate-process-step"><h3 class="wp-block-heading"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'result' ) ); ?></h3><p class="seo-geo-content-slot--case-result-body seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'case_prompt' ) ); ?></p></div></div></section><!-- /wp:group -->
<?php elseif ( 'about' === $seo_geo_pattern_key ) : ?>
<!-- wp:group {"tagName":"section","align":"wide","className":"seo-geo-corporate-native-section seo-geo-corporate-about-feature","layout":{"type":"constrained"}} --><section class="wp-block-group alignwide seo-geo-corporate-native-section seo-geo-corporate-about-feature"><div class="wp-block-columns are-vertically-aligned-center seo-geo-corporate-about-feature__grid"><div class="wp-block-column is-vertically-aligned-center"><p class="seo-geo-corporate-eyebrow"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'story_label' ) ); ?></p><h2 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'story_title' ) ); ?></h2><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'story_body' ) ); ?></p></div><div class="wp-block-column is-vertically-aligned-center"><figure class="wp-block-image size-full seo-geo-corporate-mockup-media seo-geo-placeholder--media"><img src="<?php echo esc_url( $seo_geo_asset . 'placeholder-about.svg' ); ?>" alt="" width="1200" height="760" loading="lazy" decoding="async"/></figure></div></div></section><!-- /wp:group -->
<!-- wp:group {"tagName":"section","align":"wide","className":"seo-geo-corporate-native-section","layout":{"type":"constrained"}} --><section class="wp-block-group alignwide seo-geo-corporate-native-section"><div class="wp-block-group seo-geo-corporate-section-heading"><p class="seo-geo-corporate-eyebrow"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'author_label' ) ); ?></p><h2 class="wp-block-heading seo-geo-content-slot--author-name seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'author_name' ) ); ?></h2><p class="seo-geo-content-slot--author-role seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'author_role' ) ); ?></p></div><div class="wp-block-columns"><div class="wp-block-column"><p class="seo-geo-content-slot--author-bio seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'author_bio' ) ); ?></p></div></div></section><!-- /wp:group -->
<!-- wp:group {"tagName":"section","align":"full","className":"seo-geo-corporate-native-process","layout":{"type":"constrained"}} --><section class="wp-block-group alignfull seo-geo-corporate-native-process"><p class="seo-geo-corporate-eyebrow"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'process_label' ) ); ?></p><h2 class="wp-block-heading seo-geo-content-slot--process-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'process_title' ) ); ?></h2><div class="wp-block-columns seo-geo-corporate-process-grid"><div class="wp-block-column seo-geo-corporate-process-step"><p class="seo-geo-corporate-process-step__number">01</p><h3 class="wp-block-heading seo-geo-content-slot--process-1-title seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'process_1' ) ); ?></h3></div><div class="wp-block-column seo-geo-corporate-process-step"><p class="seo-geo-corporate-process-step__number">02</p><h3 class="wp-block-heading seo-geo-content-slot--process-2-title seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'process_2' ) ); ?></h3></div><div class="wp-block-column seo-geo-corporate-process-step"><p class="seo-geo-corporate-process-step__number">03</p><h3 class="wp-block-heading seo-geo-content-slot--process-3-title seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'process_3' ) ); ?></h3></div></div></section><!-- /wp:group -->
<?php elseif ( 'contact' === $seo_geo_pattern_key ) : ?>
<!-- wp:group {"tagName":"section","align":"wide","className":"seo-geo-corporate-native-section","layout":{"type":"constrained"}} --><section class="wp-block-group alignwide seo-geo-corporate-native-section"><div class="wp-block-group seo-geo-corporate-section-heading"><p class="seo-geo-corporate-eyebrow"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'contact_label' ) ); ?></p><h2 class="wp-block-heading seo-geo-content-slot--contact-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'contact_title' ) ); ?></h2><p class="seo-geo-content-slot--contact-intro seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'contact_body' ) ); ?></p></div><div class="wp-block-columns seo-geo-corporate-card-grid"><div class="wp-block-column seo-geo-corporate-card seo-geo-corporate-card--featured"><p class="seo-geo-corporate-card__index">01</p><h3 class="wp-block-heading"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'email_title' ) ); ?></h3><p class="seo-geo-content-slot--contact-email seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'email_body' ) ); ?></p></div><div class="wp-block-column seo-geo-corporate-card"><p class="seo-geo-corporate-card__index">02</p><h3 class="wp-block-heading"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'phone_title' ) ); ?></h3><p class="seo-geo-content-slot--contact-phone seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'phone_body' ) ); ?></p></div><div class="wp-block-column seo-geo-corporate-card"><p class="seo-geo-corporate-card__index">03</p><h3 class="wp-block-heading"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'area_title' ) ); ?></h3><p class="seo-geo-content-slot--contact-area seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'area_body' ) ); ?></p></div></div></section><!-- /wp:group -->
<!-- wp:group {"tagName":"section","align":"wide","className":"seo-geo-corporate-native-section seo-geo-corporate-about-feature","layout":{"type":"constrained"}} --><section class="wp-block-group alignwide seo-geo-corporate-native-section seo-geo-corporate-about-feature"><div class="wp-block-columns are-vertically-aligned-center seo-geo-corporate-about-feature__grid"><div class="wp-block-column is-vertically-aligned-center"><p class="seo-geo-corporate-eyebrow"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'expect_label' ) ); ?></p><h2 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'expect_title' ) ); ?></h2><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'expect_body' ) ); ?></p></div><div class="wp-block-column is-vertically-aligned-center"><figure class="wp-block-image size-full seo-geo-corporate-mockup-media seo-geo-placeholder--media"><img src="<?php echo esc_url( $seo_geo_asset . 'placeholder-about.svg' ); ?>" alt="" width="1200" height="760" loading="lazy" decoding="async"/></figure></div></div></section><!-- /wp:group -->
<?php elseif ( 'insights' === $seo_geo_pattern_key ) : ?>
<!-- wp:group {"tagName":"section","align":"wide","className":"seo-geo-corporate-native-section","layout":{"type":"constrained"}} --><section class="wp-block-group alignwide seo-geo-corporate-native-section"><div class="wp-block-group seo-geo-corporate-section-heading"><p class="seo-geo-corporate-eyebrow"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'feed_label' ) ); ?></p><h2 class="wp-block-heading"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'feed_title' ) ); ?></h2><p><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'feed_body' ) ); ?></p></div><!-- wp:query {"query":{"perPage":6,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false},"align":"wide"} --><div class="wp-block-query alignwide"><!-- wp:post-template {"layout":{"type":"grid","columnCount":3}} --><!-- wp:group {"className":"seo-geo-corporate-card","layout":{"type":"constrained"}} --><div class="wp-block-group seo-geo-corporate-card"><!-- wp:post-featured-image {"isLink":true,"aspectRatio":"16/9"} /--><!-- wp:post-date {"fontSize":"sm"} /--><!-- wp:post-title {"isLink":true,"level":3} /--><!-- wp:post-excerpt {"moreText":""} /--></div><!-- /wp:group --><!-- /wp:post-template --><!-- wp:query-no-results --><p><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'empty' ) ); ?></p><!-- /wp:query-no-results --><!-- wp:query-pagination {"layout":{"type":"flex","justifyContent":"space-between"}} --><!-- wp:query-pagination-previous /--><!-- wp:query-pagination-numbers /--><!-- wp:query-pagination-next /--><!-- /wp:query-pagination --></div><!-- /wp:query --></section><!-- /wp:group -->
<?php endif; ?>

<!-- wp:group {"tagName":"section","align":"full","className":"seo-geo-final-cta","layout":{"type":"constrained"}} -->
<section class="wp-block-group alignfull seo-geo-final-cta"><h2 class="wp-block-heading seo-geo-content-slot--final-cta-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'cta_title' ) ); ?></h2><p class="seo-geo-content-slot--final-cta-body seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'cta_body' ) ); ?></p><div class="wp-block-buttons"><div class="wp-block-button seo-geo-content-slot--final-cta-button seo-geo-placeholder--copy"><a class="wp-block-button__link wp-element-button" href="#contacto"><?php echo esc_html( $seo_geo_text( $seo_geo_page, 'cta_button' ) ); ?></a></div></div></section>
<!-- /wp:group -->
