<?php
/**
 * SaaS / Digital Product final Home mockup.
 *
 * The page-level H1 remains owned by front-page.html. This composition starts
 * below that title and supplies the finished product-facing information system.
 *
 * @package SeoGeoTheme
 */

declare(strict_types=1);

$seo_geo_saas_copy_path = seo_geo_theme_preset_root() . '/saas-digital-product/mockup-copy.json';
$seo_geo_saas_copy_doc  = is_readable( $seo_geo_saas_copy_path ) && function_exists( 'wp_json_file_decode' )
	? wp_json_file_decode( $seo_geo_saas_copy_path, array( 'associative' => true ) )
	: null;

if ( ! is_array( $seo_geo_saas_copy_doc ) || ! is_array( $seo_geo_saas_copy_doc['en_US'] ?? null ) ) {
	return;
}

$seo_geo_saas_locale   = seo_geo_theme_preset_locale();
$seo_geo_saas_fallback = $seo_geo_saas_copy_doc['en_US'];
$seo_geo_saas_current  = $seo_geo_saas_copy_doc[ $seo_geo_saas_locale ] ?? null;
$seo_geo_saas_copy     = is_array( $seo_geo_saas_current )
	? array_merge( $seo_geo_saas_fallback, $seo_geo_saas_current )
	: $seo_geo_saas_fallback;
?>
<!-- wp:group {"tagName":"section","align":"wide","className":"seo-geo-saas-home seo-geo-saas-hero seo-geo-layout-shell","layout":{"type":"constrained"}} -->
<section class="wp-block-group alignwide seo-geo-saas-home seo-geo-saas-hero seo-geo-layout-shell">
	<!-- wp:columns {"verticalAlignment":"center","className":"seo-geo-saas-hero__grid"} -->
	<div class="wp-block-columns are-vertically-aligned-center seo-geo-saas-hero__grid">
		<!-- wp:column {"verticalAlignment":"center"} -->
		<div class="wp-block-column is-vertically-aligned-center"><!-- wp:group {"className":"seo-geo-saas-hero__copy seo-geo-safe-copy","layout":{"type":"constrained"}} --><div class="wp-block-group seo-geo-saas-hero__copy seo-geo-safe-copy">
			<!-- wp:paragraph {"className":"seo-geo-saas-kicker seo-geo-content-slot--hero-eyebrow seo-geo-placeholder--copy"} --><p class="seo-geo-saas-kicker seo-geo-content-slot--hero-eyebrow seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['kicker'] ); ?></p><!-- /wp:paragraph -->
			<!-- wp:paragraph {"className":"seo-geo-saas-lead seo-geo-content-slot--hero-lead seo-geo-placeholder--copy"} --><p class="seo-geo-saas-lead seo-geo-content-slot--hero-lead seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['lead'] ); ?></p><!-- /wp:paragraph -->
			<!-- wp:buttons {"className":"seo-geo-saas-actions"} --><div class="wp-block-buttons seo-geo-saas-actions"><!-- wp:button {"className":"seo-geo-content-slot--hero-primary-cta seo-geo-placeholder--copy"} --><div class="wp-block-button seo-geo-content-slot--hero-primary-cta seo-geo-placeholder--copy"><a class="wp-block-button__link wp-element-button" href="#contact-demo"><?php echo esc_html( $seo_geo_saas_copy['primary'] ); ?></a></div><!-- /wp:button --><!-- wp:button {"className":"is-style-outline seo-geo-content-slot--hero-secondary-cta seo-geo-placeholder--copy"} --><div class="wp-block-button is-style-outline seo-geo-content-slot--hero-secondary-cta seo-geo-placeholder--copy"><a class="wp-block-button__link wp-element-button" href="#como-funciona"><?php echo esc_html( $seo_geo_saas_copy['secondary'] ); ?></a></div><!-- /wp:button --></div><!-- /wp:buttons -->
		</div><!-- /wp:group --></div>
		<!-- /wp:column -->
		<!-- wp:column {"verticalAlignment":"center"} -->
		<div class="wp-block-column is-vertically-aligned-center"><!-- wp:group {"className":"seo-geo-saas-product-frame seo-geo-content-slot--product-visual seo-geo-placeholder--media","layout":{"type":"default"}} --><div class="wp-block-group seo-geo-saas-product-frame seo-geo-content-slot--product-visual seo-geo-placeholder--media">
			<!-- wp:group {"className":"seo-geo-saas-product-frame__rail","layout":{"type":"default"}} --><div class="wp-block-group seo-geo-saas-product-frame__rail"></div><!-- /wp:group -->
			<!-- wp:group {"className":"seo-geo-saas-product-frame__canvas","layout":{"type":"default"}} --><div class="wp-block-group seo-geo-saas-product-frame__canvas"><!-- wp:group {"className":"seo-geo-saas-product-frame__panel","layout":{"type":"default"}} --><div class="wp-block-group seo-geo-saas-product-frame__panel"></div><!-- /wp:group --><!-- wp:group {"className":"seo-geo-saas-product-frame__metrics","layout":{"type":"default"}} --><div class="wp-block-group seo-geo-saas-product-frame__metrics"><!-- wp:group {"className":"seo-geo-saas-product-frame__metric","layout":{"type":"default"}} --><div class="wp-block-group seo-geo-saas-product-frame__metric"></div><!-- /wp:group --><!-- wp:group {"className":"seo-geo-saas-product-frame__metric","layout":{"type":"default"}} --><div class="wp-block-group seo-geo-saas-product-frame__metric"></div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:group -->
		</div><!-- /wp:group --><!-- wp:paragraph {"className":"seo-geo-saas-kicker"} --><p class="seo-geo-saas-kicker"><?php echo esc_html( $seo_geo_saas_copy['preview_label'] ); ?></p><!-- /wp:paragraph --><!-- wp:paragraph {"fontSize":"xs","className":"seo-geo-placeholder--copy"} --><p class="has-xs-font-size seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['preview_note'] ); ?></p><!-- /wp:paragraph --></div>
		<!-- /wp:column -->
	</div>
	<!-- /wp:columns -->
</section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","align":"full","className":"seo-geo-saas-section seo-geo-saas-section--surface","layout":{"type":"constrained"}} -->
<section class="wp-block-group alignfull seo-geo-saas-section seo-geo-saas-section--surface"><!-- wp:group {"className":"seo-geo-layout-shell","layout":{"type":"constrained"}} --><div class="wp-block-group seo-geo-layout-shell">
	<!-- wp:group {"className":"seo-geo-saas-section__heading seo-geo-safe-copy","layout":{"type":"constrained"}} --><div class="wp-block-group seo-geo-saas-section__heading seo-geo-safe-copy"><!-- wp:paragraph {"className":"seo-geo-saas-kicker"} --><p class="seo-geo-saas-kicker"><?php echo esc_html( $seo_geo_saas_copy['value_label'] ); ?></p><!-- /wp:paragraph --><!-- wp:heading {"level":2,"className":"seo-geo-content-slot--value-heading seo-geo-placeholder--copy"} --><h2 class="wp-block-heading seo-geo-content-slot--value-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['value_title'] ); ?></h2><!-- /wp:heading --><!-- wp:paragraph {"className":"seo-geo-content-slot--value-intro seo-geo-placeholder--copy"} --><p class="seo-geo-content-slot--value-intro seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['value_intro'] ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group -->
	<!-- wp:group {"className":"seo-geo-bento","layout":{"type":"default"}} --><div class="wp-block-group seo-geo-bento"><!-- wp:group {"className":"seo-geo-saas-card seo-geo-saas-card--primary seo-geo-surface-card","layout":{"type":"constrained"}} --><div class="wp-block-group seo-geo-saas-card seo-geo-saas-card--primary seo-geo-surface-card"><p class="seo-geo-saas-card__label">01</p><h3 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['problem'] ); ?></h3><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['problem_body'] ); ?></p></div><!-- /wp:group --><!-- wp:group {"className":"seo-geo-saas-card seo-geo-surface-card","layout":{"type":"constrained"}} --><div class="wp-block-group seo-geo-saas-card seo-geo-surface-card"><p class="seo-geo-saas-card__label">02</p><h3 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['workflow'] ); ?></h3><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['workflow_body'] ); ?></p></div><!-- /wp:group --><!-- wp:group {"className":"seo-geo-saas-card seo-geo-surface-card","layout":{"type":"constrained"}} --><div class="wp-block-group seo-geo-saas-card seo-geo-surface-card"><p class="seo-geo-saas-card__label">03</p><h3 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['outcome'] ); ?></h3><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['outcome_body'] ); ?></p></div><!-- /wp:group --></div><!-- /wp:group -->
</div><!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","align":"wide","anchor":"como-funciona","className":"seo-geo-saas-section seo-geo-layout-shell","layout":{"type":"constrained"}} -->
<section id="como-funciona" class="wp-block-group alignwide seo-geo-saas-section seo-geo-layout-shell"><!-- wp:group {"className":"seo-geo-saas-section__heading","layout":{"type":"constrained"}} --><div class="wp-block-group seo-geo-saas-section__heading"><p class="seo-geo-saas-kicker"><?php echo esc_html( $seo_geo_saas_copy['flow_label'] ); ?></p><h2 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['flow_title'] ); ?></h2><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['flow_intro'] ); ?></p></div><!-- /wp:group --><!-- wp:group {"className":"seo-geo-process-sequence seo-geo-saas-flow","layout":{"type":"default"}} --><div class="wp-block-group seo-geo-process-sequence seo-geo-saas-flow"><!-- wp:group {"layout":{"type":"constrained"}} --><div class="wp-block-group"><h3 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['step_1'] ); ?></h3><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['step_1_body'] ); ?></p></div><!-- /wp:group --><!-- wp:group {"layout":{"type":"constrained"}} --><div class="wp-block-group"><h3 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['step_2'] ); ?></h3><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['step_2_body'] ); ?></p></div><!-- /wp:group --><!-- wp:group {"layout":{"type":"constrained"}} --><div class="wp-block-group"><h3 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['step_3'] ); ?></h3><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['step_3_body'] ); ?></p></div><!-- /wp:group --></div><!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","align":"full","className":"seo-geo-saas-section seo-geo-saas-section--surface","layout":{"type":"constrained"}} -->
<section class="wp-block-group alignfull seo-geo-saas-section seo-geo-saas-section--surface"><!-- wp:columns {"verticalAlignment":"center","className":"seo-geo-layout-shell seo-geo-saas-split"} --><div class="wp-block-columns are-vertically-aligned-center seo-geo-layout-shell seo-geo-saas-split"><!-- wp:column {"verticalAlignment":"center"} --><div class="wp-block-column is-vertically-aligned-center"><p class="seo-geo-saas-kicker"><?php echo esc_html( $seo_geo_saas_copy['integration_label'] ); ?></p><h2 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['integration_title'] ); ?></h2><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['integration_body'] ); ?></p></div><!-- /wp:column --><!-- wp:column {"verticalAlignment":"center"} --><div class="wp-block-column is-vertically-aligned-center"><!-- wp:group {"className":"seo-geo-saas-proof-placeholder seo-geo-placeholder--copy","layout":{"type":"constrained"}} --><div class="wp-block-group seo-geo-saas-proof-placeholder seo-geo-placeholder--copy"><p><?php echo esc_html( $seo_geo_saas_copy['integration_empty'] ); ?></p></div><!-- /wp:group --></div><!-- /wp:column --></div><!-- /wp:columns --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","align":"wide","className":"seo-geo-saas-section seo-geo-layout-shell","layout":{"type":"constrained"}} -->
<section class="wp-block-group alignwide seo-geo-saas-section seo-geo-layout-shell"><!-- wp:group {"className":"seo-geo-saas-section__heading","layout":{"type":"constrained"}} --><div class="wp-block-group seo-geo-saas-section__heading"><p class="seo-geo-saas-kicker"><?php echo esc_html( $seo_geo_saas_copy['cases_label'] ); ?></p><h2 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['cases_title'] ); ?></h2></div><!-- /wp:group --><!-- wp:group {"className":"seo-geo-saas-use-cases","layout":{"type":"default"}} --><div class="wp-block-group seo-geo-saas-use-cases"><!-- wp:group {"className":"seo-geo-saas-card seo-geo-surface-card","layout":{"type":"constrained"}} --><div class="wp-block-group seo-geo-saas-card seo-geo-surface-card"><h3 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['case_1'] ); ?></h3><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['case_1_body'] ); ?></p></div><!-- /wp:group --><!-- wp:group {"className":"seo-geo-saas-card seo-geo-surface-card","layout":{"type":"constrained"}} --><div class="wp-block-group seo-geo-saas-card seo-geo-surface-card"><h3 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['case_2'] ); ?></h3><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['case_2_body'] ); ?></p></div><!-- /wp:group --><!-- wp:group {"className":"seo-geo-saas-card seo-geo-surface-card","layout":{"type":"constrained"}} --><div class="wp-block-group seo-geo-saas-card seo-geo-surface-card"><h3 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['case_3'] ); ?></h3><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['case_3_body'] ); ?></p></div><!-- /wp:group --></div><!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","align":"full","className":"seo-geo-saas-section seo-geo-saas-section--surface","layout":{"type":"constrained"}} -->
<section class="wp-block-group alignfull seo-geo-saas-section seo-geo-saas-section--surface"><!-- wp:group {"className":"seo-geo-layout-shell","layout":{"type":"constrained"}} --><div class="wp-block-group seo-geo-layout-shell"><!-- wp:group {"className":"seo-geo-saas-section__heading","layout":{"type":"constrained"}} --><div class="wp-block-group seo-geo-saas-section__heading"><p class="seo-geo-saas-kicker"><?php echo esc_html( $seo_geo_saas_copy['plans_label'] ); ?></p><h2 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['plans_title'] ); ?></h2><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['plans_body'] ); ?></p></div><!-- /wp:group --><!-- wp:columns {"className":"seo-geo-saas-split"} --><div class="wp-block-columns seo-geo-saas-split"><!-- wp:column {"className":"seo-geo-saas-card seo-geo-surface-card seo-geo-placeholder--copy"} --><div class="wp-block-column seo-geo-saas-card seo-geo-surface-card seo-geo-placeholder--copy"><h3 class="wp-block-heading"><?php echo esc_html( $seo_geo_saas_copy['plan_1'] ); ?></h3><p><?php echo esc_html( $seo_geo_saas_copy['plan_1_body'] ); ?></p></div><!-- /wp:column --><!-- wp:column {"className":"seo-geo-saas-card seo-geo-surface-card seo-geo-placeholder--copy"} --><div class="wp-block-column seo-geo-saas-card seo-geo-surface-card seo-geo-placeholder--copy"><h3 class="wp-block-heading"><?php echo esc_html( $seo_geo_saas_copy['plan_2'] ); ?></h3><p><?php echo esc_html( $seo_geo_saas_copy['plan_2_body'] ); ?></p></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","align":"wide","className":"seo-geo-saas-section seo-geo-layout-shell seo-geo-saas-faq","layout":{"type":"constrained"}} -->
<section class="wp-block-group alignwide seo-geo-saas-section seo-geo-layout-shell seo-geo-saas-faq"><p class="seo-geo-saas-kicker"><?php echo esc_html( $seo_geo_saas_copy['faq_label'] ); ?></p><h2 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['faq_title'] ); ?></h2><!-- wp:details --><details class="wp-block-details"><summary><?php echo esc_html( $seo_geo_saas_copy['faq_1'] ); ?></summary><!-- wp:paragraph {"className":"seo-geo-placeholder--copy"} --><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['faq_1_body'] ); ?></p><!-- /wp:paragraph --></details><!-- /wp:details --><!-- wp:details --><details class="wp-block-details"><summary><?php echo esc_html( $seo_geo_saas_copy['faq_2'] ); ?></summary><!-- wp:paragraph {"className":"seo-geo-placeholder--copy"} --><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['faq_2_body'] ); ?></p><!-- /wp:paragraph --></details><!-- /wp:details --><!-- wp:details --><details class="wp-block-details"><summary><?php echo esc_html( $seo_geo_saas_copy['faq_3'] ); ?></summary><!-- wp:paragraph {"className":"seo-geo-placeholder--copy"} --><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['faq_3_body'] ); ?></p><!-- /wp:paragraph --></details><!-- /wp:details --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","align":"wide","anchor":"contact-demo","className":"seo-geo-final-cta seo-geo-saas-final-cta seo-geo-safe-copy","layout":{"type":"constrained"}} -->
<section id="contact-demo" class="wp-block-group alignwide seo-geo-final-cta seo-geo-saas-final-cta seo-geo-safe-copy"><h2 class="wp-block-heading seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['cta_title'] ); ?></h2><p class="seo-geo-placeholder--copy"><?php echo esc_html( $seo_geo_saas_copy['cta_body'] ); ?></p><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"seo-geo-placeholder--copy"} --><div class="wp-block-button seo-geo-placeholder--copy"><a class="wp-block-button__link wp-element-button" href="#"><?php echo esc_html( $seo_geo_saas_copy['cta_button'] ); ?></a></div><!-- /wp:button --></div><!-- /wp:buttons --></section>
<!-- /wp:group -->
